"""1st rev

Revision ID: 8621421a80e1
Revises: cfa240018469
Create Date: 2023-09-16 11:50:03.399571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8621421a80e1'
down_revision: Union[str, None] = 'cfa240018469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('city_timestamp',
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('main_weather',
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('feels_like', sa.Float(), nullable=True),
    sa.Column('grnd_level', sa.Integer(), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('pressure', sa.Integer(), nullable=True),
    sa.Column('sea_level', sa.Integer(), nullable=True),
    sa.Column('temp', sa.Float(), nullable=True),
    sa.Column('temp_max', sa.Float(), nullable=True),
    sa.Column('temp_min', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id')
    )
    op.create_table('extra_weather',
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.Integer(), nullable=True),
    sa.Column('wind', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['main_weather.city_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extra_weather')
    op.drop_table('main_weather')
    op.drop_table('city_timestamp')
    op.drop_table('city')
    # ### end Alembic commands ###
