"""2 rev

Revision ID: d1664d07d9f8
Revises: 8621421a80e1
Create Date: 2023-09-17 13:43:46.601102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1664d07d9f8'
down_revision: Union[str, None] = '8621421a80e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'city', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'city', type_='unique')
    # ### end Alembic commands ###
